language: go
sudo: false

matrix:
  include:
    - os: linux
      go: "1.11.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: linux
      go: "1.12.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: linux
      go: "1.13.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    # only run fuse and cloud backends tests on Travis for the latest Go on Linux
    - os: linux
      go: "1.14.x"
      sudo: true
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.14.x"
      env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

    # Cross-compilation job; doesn't run any tests.
    - name: Cross-compile
      os: linux
      go: "1.14.x"
      script: cd cmd/restic && go env GOARCH GOOS && go build -tags=debug
      env:
        - GOARCH=amd64 GOOS=freebsd
        - GOARCH=amd64 GOOS=illumos
        - GOARCH=arm64 GOOS=linux
        - GOARCH=amd64 GOOS=netbsd
        - GOARCH=amd64 GOOS=openbsd

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - go run run_integration_tests.go
