language: go
sudo: false

go:
  - 1.9.x

os:
  - linux

env:
  matrix:
    RESTIC_TEST_FUSE=0

matrix:
  include:
    - os: linux
      go: 1.9.x
      sudo: false
      env:
        RESTIC_TEST_FUSE=1

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - DEBUG_LOG=debug.log go test -tags debug -v -run TestBackendSwift/TestSwift ./internal/backend/swift

after_failure:
  - cat debug.log

after_success:
  - bash <(curl -s https://codecov.io/bash) -f all.cov
