language: go
go:
  - 1.3.3
  - 1.4.2
  - release

os:
  - linux
  - osx

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change

install:
  - go get github.com/tools/godep
  - godep restore
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -os "linux darwin"

script:
  - godep go build -ldflags "-s" ./...
  - godep go build -ldflags "-s" -o restic ./cmd/restic
  - sh -c "cd cmd/restic && gox -verbose -os 'linux darwin' && ls -al"
  - godep go test -v ./...
  - ./testsuite.sh
  - sh -c "cd backend && godep go test -v -test.sftppath /usr/lib/openssh/sftp-server ./..."
  - gofmt -l *.go */*.go */*/*.go
  - test -z "$(gofmt -l *.go */*.go */*/*.go)"
